# Form implementation generated from reading ui file 'c:\Qt\bioFinal\GUIui\generalInfo.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_generalInfoWindow(object):
    def setupUi(self, generalInfoWindow):
        generalInfoWindow.setObjectName("generalInfoWindow")
        generalInfoWindow.resize(645, 367)
        generalInfoWindow.setStyleSheet("background-color: white")
        self.centralwidget = QtWidgets.QWidget(parent=generalInfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 601, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 80, 601, 191))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 601, 191))
        self.textBrowser.setObjectName("textBrowser")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.exportBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exportBtn.setGeometry(QtCore.QRect(20, 280, 601, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.exportBtn.setFont(font)
        self.exportBtn.setStyleSheet("background-color: rgb(225, 247, 240);")
        self.exportBtn.setObjectName("exportBtn")
        generalInfoWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=generalInfoWindow)
        self.statusbar.setObjectName("statusbar")
        generalInfoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(generalInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(generalInfoWindow)

    def retranslateUi(self, generalInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        generalInfoWindow.setWindowTitle(_translate("generalInfoWindow", "MainWindow"))
        self.exportBtn.setText(_translate("generalInfoWindow", "Export Information as Pdf"))
